export const criminalCrimeTypes = [
    { label: "Aggravated Assault", value: "Aggravated Assault" },
    { label: "Arson", value: "Arson" },
    // { label: "Assault", value: "Assault" },
    // { label: "Attempt", value: "Attempt" },
    { label: "Bribery", value: "Bribery" },
    { label: "Burglary", value: "Burglary" },
    { label: "Child Abandonment", value: "Child Abandonment" },
    { label: "Child Abuse", value: "Child Abuse" },
    { label: "Child Pornography", value: "Child Pornography" },
    { label: "Computer Crime", value: "Computer Crime" },
    // { label: "Conspiracy", value: "Conspiracy" },
    // {
    //     label: "Credit / Debit Card Fraud",
    //     value: "Credit / Debit Card Fraud",
    // },
    // {
    //     label: "Criminal Contempt of Court",
    //     value: "Criminal Contempt of Court",
    // },
    { label: "Cyberbullying", value: "Cyberbullying" },
    // { label: "Disorderly Conduct", value: "Disorderly Conduct" },
    // { label: "Disturbing the Peace", value: "Disturbing the Peace" },
    // { label: "Domestic Violence", value: "Domestic Violence" },
    { label: "Drug Possession", value: "Drug Possession" },
    {
        label: "Drug Smuggling",
        value: "Drug Smuggling",
    },
    {
        label: "Drug Trafficking",
        value: "Drug Trafficking",
    },
    // { label: "DUI / DWI", value: "DUI / DWI" },
    // { label: "Embezzlement", value: "Embezzlement" },
    // { label: "Embezzlement", value: "Embezzlement" },
    { label: "Extortion", value: "Extortion" },
    { label: "Forgery", value: "Forgery" },
    { label: "Fraud", value: "Fraud" },
    { label: "Harassment", value: "Harassment" },
    // { label: "Hate Crimes", value: "Hate Crimes" },
    { label: "Homicide", value: "Homicide" },
    // { label: "Identity Theft", value: "Identity Theft" },
    // { label: "Indecent Exposure", value: "Indecent Exposure" },
    // { label: "Insurance Fraud", value: "Insurance Fraud" },
    { label: "Kidnapping", value: "Kidnapping" },
    { label: "Manslaughter", value: "Manslaughter" },
    { label: "Medical Marijuana", value: "Medical Marijuana" },
    // { label: "Minor in Possession", value: " Minor in Possession" },
    { label: "Money Laundering", value: "Money Laundering" },
    { label: "Murder", value: "Murder" },
    // {
    //     label: "Open Container (of alcohol)",
    //     value: "Open Container (of alcohol)",
    // },
    { label: "Perjury", value: "Perjury" },
    // { label: "Probation Violation", value: "Probation Violation" },
    { label: "Prostitution", value: "Prostitution" },
    { label: "Public Intoxication", value: "Public Intoxication" },
    { label: "Pyramid Schemes", value: "Pyramid Schemes" },
    // { label: "Racketeering / RICO", value: "Racketeering / RICO" },
    { label: "Rape", value: "Rape" },
    // { label: "Robbery", value: "Robbery" },
    // { label: "Securities Fraud", value: "Securities Fraud" },
    // { label: "Sexual Assault", value: "Sexual Assault" },
    // { label: "Shoplifting", value: "Sexual Shoplifting" },
    { label: "Solicitation", value: "Solicitation" },
    { label: "Stalking", value: "Stalking" },
    { label: "Statutory Rape", value: "Statutory Rape" },
    // { label: "Tax Evasion", value: "Tax Evasion" },
    // { label: "Telemarketing Fraud", value: "Telemarketing Fraud" },
    // { label: "Theft", value: "Theft" },
    { label: "Vandalism", value: "Vandalism" },
    // { label: "White Collar Crimes", value: "White Collar Crimes" },
    // { label: "Wire Fraud", value: "Wire Fraud" },
]

export const civilCrimeTypes = [
    {label: "Annulment of auction sale", value: "Annulment of auction sale"},
    {label: "Annulment of documents", value: "Annulment of documents"},
    {label: "Annulment of foreclosure sale", value: "Annulment of foreclosure"},
    {label: "Annulment of judgment", value: "Annulment of judgment"},
    {label: "Annulment of marriage ", value: "Annulment of marriage"},
    {label: "Annulment of mortgage", value: "Annulment of mortgage"},
    {label: "Annulment of sale", value: "Annulment of sale"},
    {label: "Annulment of tax sale", value: "Annulment of tax sale"},
    {label: "Annulment of title", value: "Annulment of title"},
    {label: "Breach of contract", value: "Breach contract"},
    {label: "Cancellation of adverse claim", value:"Cancellation of adverse claim"},
    {label: "Cancellation of encumbrance", value: "Cancellation of encumbrances"},
    {label: "Cancellation of entry", value: "Cancellation of entry"},
    {label: "Cancellation of lien", value: "Cancellation of lien"},
    {label: "Cancellation of title", value: "Cancellation of title"},
    {label: "Consolidation of ownership", value: "Consolidation of ownership"},
    {label: "Damages", value: "Damages"},
    {label: "Easement", value: "Easement"},
    {label: "Ejectment", value: "Ejectment"},
    {label: "Exclusion", value: "Exclusion"},
    {label: "Injunction", value: "Injunction"},
    {label: "Insurance of owner's duplicate TCT", value: "Insurance of owner's duplicate TCT"},
    {label: "Just compensation", value: "Just compensation"},
    {label: "Reconveyance", value: "Reconveyance"}
]